# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - hello-world-app-to-delete

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'

    - name: npm install and build
      run: |
        npm install
        npm run build --prod
      
      working-directory: .

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'rickandmorty-ui'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AE9E17C3F83B4ACEBF583050EE34DEF2 }}
        package: ./dist/rick-and-morty-ui